ALTER TABLE books
ADD COLUMN description VARCHAR(255),
ADD COLUMN publisher VARCHAR(255),
ADD COLUMN publishedDate date,
ADD COLUMN smallThumbnail VARCHAR(255),
ADD COLUMN thumbnail VARCHAR(255),
ADD COLUMN googleBookID VARCHAR(255);